# Generated by Django 6.0.2 on 2026-03-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LOTUS Learn', max_length=200)),
                ('hero_title', models.CharField(default='AI-Based Learning Platform', max_length=255)),
                ('hero_subtitle', models.TextField(default='Хиймэл оюунд суурилсан шатлалтай сургалтын систем.')),
                ('about_title', models.CharField(blank=True, default='Системийн тухай', max_length=255)),
                ('about_text', models.TextField(blank=True, default='Энэхүү систем нь суралцагчийн түвшин, ахиц, сонирхолд тулгуурлан сургалтын материалыг илүү үр дүнтэй хүргэх зорилготой.')),
                ('feature_1_title', models.CharField(blank=True, default='AI Summary', max_length=255)),
                ('feature_1_text', models.TextField(blank=True, default='Хичээлийн агуулгыг товч бөгөөд ойлгомжтой хураангуйлна.')),
                ('feature_2_title', models.CharField(blank=True, default='Adaptive Learning', max_length=255)),
                ('feature_2_text', models.TextField(blank=True, default='Хэрэглэгчийн түвшинд тохирсон сургалтын зам санал болгоно.')),
                ('feature_3_title', models.CharField(blank=True, default='Community', max_length=255)),
                ('feature_3_text', models.TextField(blank=True, default='Хэрэглэгчид хоорондоо хичээлтэй холбоотой санал бодлоо солилцоно.')),
                ('slide_image_1', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('slide_image_2', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('slide_image_3', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
    ]
