version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: elearn
      POSTGRES_USER: elearn
      POSTGRES_PASSWORD: elearn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elearn"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: sh wait-for-db.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: elearn
      DB_USER: elearn
      DB_PASSWORD: elearn
      DB_HOST: db
      DB_PORT: 5432

      GEMINI_API_KEY: "${GEMINI_API_KEY}"

volumes:
  postgres_data: