# Generated by Django 6.0.2 on 2026-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='score',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
