# Generated by Django 6.0.2 on 2026-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_lessonprogress_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
