# Generated by Django 6.0.2 on 2026-04-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0003_alter_lessonprogress_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="practice_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="practice_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="practice_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="practice_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
