# Generated by Django 6.0.2 on 2026-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_created_at_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='score',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
