# Generated by Django 6.0.2 on 2026-03-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_attachment_lesson_file_lesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Анхан'), ('elementary', 'Суурь'), ('intermediate', 'Дунд'), ('advanced', 'Ахисан')], default='beginner', max_length=20),
        ),
    ]
