# Generated by Django 6.0.2 on 2026-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_learningtrack_course_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='practice_bonus_score',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_expected_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_hint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
