# Generated by Django 6.0.2 on 2026-03-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='moderation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='moderation_status',
            field=models.CharField(choices=[('allow', 'Allow'), ('review', 'Review'), ('reject', 'Reject')], default='allow', max_length=20),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='moderation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='moderation_status',
            field=models.CharField(choices=[('allow', 'Allow'), ('review', 'Review'), ('reject', 'Reject')], default='allow', max_length=20),
        ),
    ]
