# Generated by Django 6.0.2 on 2026-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_placement_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, null=True),
        ),
    ]
