# Generated by Django 6.0.2 on 2026-03-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_placement_test_alter_user_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Анхан'), ('elementary', 'Суурь'), ('intermediate', 'Дунд'), ('advanced', 'Ахисан')], default='beginner', max_length=20, null=True),
        ),
    ]
